### ISSUE TITLE
Redact privileged details from the public configuration file.

### ISSUE THREAD

**Issue by skx** [beansight/beansight-website#1]
You have (valid) gmail login details stored in your repository:

https://github.com/beansight/beansight-website/blob/master/conf/application.conf

Check the facebook tokens, etc, and change all affected details.

**Comment by dyatlov** [comment]
That's not a proper way of hiding details. You should remove from git history all previous commits of this file or in other case people will get them from old commits: https://github.com/beansight/beansight-website/commit/3593863a5373208e6c7e5b514c50088d9ddc34ed

**Comment by steren** [comment]
You are right.

Password were changed. Facebook and Twitter apps are disabled since social login are not functioning properly on new host and we do not have manpower to fix it.
